---
- name: Try deploying to cluster
  become: true
  hosts: k3p4_cluster
  serial: 1

  tasks:
    # - name: Debug message
    #   debug:
    #     msg: "testing 1 2 3 ... done"

    - name: Apt Update
      apt:
        update_cache: true

    - name: Apt Upgrade
      apt:
        upgrade: dist
